package org.storm.clover.euler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * <p>
 * Answer: 4613732
 * Completed on Sun, 10 Dec 2017, 17:44
 * <p>
 * <a href="https://en.wikipedia.org/wiki/Glossary_of_climbing_terms#flash">Flash'ed</a> !!
 *
 * @TODO: functional'ize
 */
public class Problem_02 {
    public long fibonacciEvenSum(long limit) {
        return fibonacciEvenSum(1, limit);
    }

    public long fibonacciEvenSum(long startAt, long maxInclusive) {
        long prev = startAt, curr = startAt, sum;
        long evenSum = 0;

        do {
            sum = prev + curr;
            prev = curr;
            if ((curr = sum) % 2 == 0) evenSum += sum;
        } while (curr <= maxInclusive);

        return evenSum;
    }
}
